<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Export control status_exportControlStatut</name>
   <tag></tag>
   <elementGuidId>1d00d6cc-7d09-435c-9263-d54fbae87fbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='exportControlStatut']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;exportControlStatut&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exportControlStatut</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-corp[1]/app-demande-visualisation[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content_wrapper col-md-12 padding-0 ng-star-inserted&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;new-design_details-contents col-md-12 padding-0&quot;]/div[@class=&quot;collapsible-blocs&quot;]/div[@class=&quot;middle-blocs col-sm-12 col-xs-12 padding-4 col-md-6&quot;]/app-demande-creation-form[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;create-wf-root form-card-no-border&quot;]/div[@class=&quot;wf-body&quot;]/div[@class=&quot;wf-body-left&quot;]/div[@class=&quot;wf-steps full-width read-only&quot;]/div[@class=&quot;wf-step&quot;]/app-step-reference[1]/div[@class=&quot;form-root&quot;]/div[@class=&quot;content&quot;]/form[@class=&quot;ng-untouched ng-pristine&quot;]/div[@class=&quot;row margin-bottom-15&quot;]/div[@class=&quot;col-md-12&quot;]/fieldset[1]/div[@class=&quot;col-md-12 d-flex-ai-c generic-inputs__style ng-star-inserted&quot;]/div[@class=&quot;col-md-8 col-sm-12 col-xs-12 input-wrapper&quot;]/input[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='exportControlStatut']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-demande-visualisation/div/form/div[2]/div/div[2]/app-demande-creation-form/div/div/div/div/div[3]/app-step-reference/div/div/form/div[2]/div/fieldset/div[10]/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[10]/div/input</value>
   </webElementXpaths>
</WebElementEntity>
